export const logOutConstants = {
  LOG_OUT_REQUEST: 'LOG_OUT_REQUEST',
}
export const logInConstants = {
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_IN_REQUEST: 'LOG_IN_REQUEST',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
}
export const projectConstants = {
  ADD_PROJECTS_FAILURE: 'ADD_PROJECTS_FAILURE',
  ADD_PROJECTS_REQUEST: 'ADD_PROJECTS_REQUEST',
  ADD_PROJECTS_SUCCESS: 'ADD_PROJECTS_SUCCESS',

  GET_PROJECTS_FAILURE: ' GET_PROJECTS_FAILURE',
  GET_PROJECTS_REQUEST: ' GET_PROJECTS_REQUEST',
  GET_PROJECTS_SUCCESS: ' GET_PROJECTS_SUCCESS',
}
export const categoryConstants = {
  ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',
  ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',

  GET_CATEGORY_FAILURE: ' GET_CATEGORY_FAILURE',
  GET_CATEGORY_REQUEST: ' GET_CATEGORY_REQUEST',
  GET_CATEGORY_SUCCESS: ' GET_CATEGORY_SUCCESS',
}
export const typesConstants = {
  GET_TYPES_FAILURE: 'GET_TYPES_FAILURE',
  GET_TYPES_REQUEST: 'GET_TYPES_REQUEST',
  GET_TYPES_SUCCESS: 'GET_TYPES_SUCCESS',
}
